

// TOOL:     vlog2tf
// DATE:     Wed May 28 16:32:50 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   StreetFighter
// DESIGN:   StreetFighter
// FILENAME: StreetFighter_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module StreetFighter_tf();

// Inputs
    reg reset_n;
    reg clk_ctrl;
    reg clk_system;
	 reg ctrl_in;
	 reg ctrl_latch;
	 reg dir;
    reg [3:0] move_select;
	

// Outputs
    wire ctrl_out;
	 wire load_override;
	 wire override_en;
	 wire clk_sm;
	 wire [3:0] button_next, button_state;
	 wire [5:0] latch_count;
	 wire [1:0] load_state, load_next;
	 wire [2:0] move;
	 wire [5:0] clk_listen;
	 wire [15:0] override_reg;
	 
// Instantiate the UUT
    StreetFighter UUT (
		.reset_n(reset_n),
		.clk_ctrl(clk_ctrl),
		.clk_system(clk_system),
		.ctrl_in(ctrl_in),
		.ctrl_latch(ctrl_latch),
		.dir(dir),
		.move(move),
		.move_select(move_select),
		.ctrl_out(ctrl_out),
		.load_override(load_override),
		.override_en(override_en),
		.button_next(button_next),
		.button_state(button_state),
		.load_state(load_state),
		.load_next(load_next),
		.clk_sm(clk_sm),
		.clk_listen(clk_listen),
		.override_reg(override_reg),
		.latch_count(latch_count)
	 );
        

	parameter US = 1000;
	parameter MS = US*1000;
	
	parameter TINY_CYCLE = 2*US;
	parameter LATCH_CYCLE = 20*US;
	parameter CYCLE = 12*US;
	parameter WAIT  = 16666667;
	
	integer i, j, k;
	
	reg [15:0] ctrl = 16'hAAFF;
	
	always begin
		clk_system = ~clk_system;
		#(6*US);
	end
	
	initial begin
		move_select = 4'b1111;
		#(MS*2);
		
		move_select = 4'b0111;
		#(CYCLE*10);
		move_select = 4'b1111;
		
		#(WAIT*20);
		
		move_select = 4'b0111;
		#(CYCLE*10);
		move_select = 4'b1111;
	end
	
	initial begin
		/* reset signal */
		reset_n = 0; #(MS);
		reset_n = 1; 		

		forever begin
			ctrl_latch = 1;
			#(CYCLE);
			ctrl_latch = 0;
			
			/* 16 clock pulses */
			for (i = 0; i < 16; i=i+1) begin
				ctrl_in = ctrl[i];

				clk_ctrl = 1; #(CYCLE/2); clk_ctrl = 0; #(CYCLE/2);
			end
			
			clk_ctrl = 1;
			ctrl_in = 0;
			
			/* wait until the next cycle */
			#(WAIT-204);
		end
	end
	
// Initialize Inputs
// You can add your stimulus here
    initial begin
			clk_ctrl = 0;
			clk_system = 0;
			dir = 0;
			
			ctrl_latch = 0;
			ctrl_in = 0;
    end

endmodule // StreetFighter_tf